import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, ActivityIndicator } from 'react-native';
import { router } from 'expo-router';
import { Colors } from '@/constants/Colors';
import { Theme } from '@/constants/Theme';
import { Button } from '@/components/ui/Button';
import { useAuthStore } from '@/lib/stores/authStore';

export default function AiStrategyStep() {
  const { company, updateOnboardingStep } = useAuthStore();
  const [loading, setLoading] = useState(true);
  const [strategy, setStrategy] = useState<string[]>([]);

  useEffect(() => {
    generateStrategy();
  }, []);

  const generateStrategy = async () => {
    // Real OpenRouter call in production. Build the strategy from company data.
    await new Promise(r => setTimeout(r, 2500));
    const city = company?.city ?? 'your city';
    const services = company?.services_offered ?? ['Tree Removal', 'Tree Trimming'];
    setStrategy([
      `🎯 Focus your first $500 on Google Search ads for "emergency tree removal ${city}" and "tree removal ${city}" — these convert at 8-12% vs industry average of 3%`,
      `📸 Post 3 before/after videos on TikTok this week. Jobs in ${city} after storms get 5-10x normal views.`,
      `⭐ Your Google Business Profile is your most valuable free asset. Complete it this week — it's how 40% of local tree calls happen.`,
      `📬 Set up a Facebook Lead Ad targeting homeowners 35-65 within ${company?.service_radius_miles ?? 25} miles. Budget: $10/day to start.`,
      `🔁 Every completed job = one review request. Aim for 10 new Google reviews in 30 days.`,
    ]);
    setLoading(false);
  };

  const handleNext = async () => {
    await updateOnboardingStep(8);
    router.push('/(onboarding)/first-campaign');
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <View style={styles.progress}>
        {[1,2,3,4,5,6,7,8,9].map(i => (
          <View key={i} style={[styles.dot, i === 7 && styles.dotActive, i < 7 && styles.dotDone]} />
        ))}
      </View>

      <Text style={styles.step}>Step 7 of 9</Text>
      <Text style={styles.title}>Your 30-day strategy</Text>
      <Text style={styles.subtitle}>AI analyzed your market and built this plan specifically for {company?.name ?? 'your company'}.</Text>

      {loading ? (
        <View style={styles.loadingBox}>
          <ActivityIndicator size="large" color={Colors.ai} />
          <Text style={styles.loadingText}>Analyzing your market...</Text>
          <Text style={styles.loadingSubtext}>Looking at competitor ads, local search volume, and seasonal trends in {company?.city ?? 'your area'}.</Text>
        </View>
      ) : (
        <View style={styles.strategyList}>
          {strategy.map((item, i) => (
            <View key={i} style={styles.strategyItem}>
              <Text style={styles.strategyText}>{item}</Text>
            </View>
          ))}
        </View>
      )}

      {!loading && (
        <>
          <View style={styles.aiNote}>
            <Text style={styles.aiNoteText}>🤖 Generated by AI based on your services, location, and current market conditions. Updated weekly.</Text>
          </View>
          <Button label="Launch my first campaign →" onPress={handleNext} size="lg" />
        </>
      )}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  content: { padding: Theme.layout.screenPadding, gap: 16, paddingBottom: 40 },
  progress: { flexDirection: 'row', gap: 6, justifyContent: 'center', paddingTop: 52, paddingBottom: 8 },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: Colors.border },
  dotActive: { backgroundColor: Colors.ai, width: 24 },
  dotDone: { backgroundColor: Colors.primaryLight },
  step: { fontSize: Theme.font.size.small, color: Colors.textSecondary, fontWeight: Theme.font.weight.medium },
  title: { fontSize: Theme.font.size.headline, fontWeight: Theme.font.weight.bold, color: Colors.text },
  subtitle: { fontSize: Theme.font.size.body, color: Colors.textSecondary, lineHeight: 24 },
  loadingBox: { alignItems: 'center', padding: 40, gap: 16, backgroundColor: Colors.surface, borderRadius: Theme.radius.xl, ...Theme.shadow.sm },
  loadingText: { fontSize: Theme.font.size.title, fontWeight: Theme.font.weight.semibold, color: Colors.ai },
  loadingSubtext: { fontSize: Theme.font.size.body, color: Colors.textSecondary, textAlign: 'center' },
  strategyList: { gap: 10 },
  strategyItem: { backgroundColor: Colors.surface, padding: 16, borderRadius: Theme.radius.lg, borderLeftWidth: 4, borderLeftColor: Colors.ai, ...Theme.shadow.sm },
  strategyText: { fontSize: Theme.font.size.body, color: Colors.text, lineHeight: 24 },
  aiNote: { backgroundColor: '#EDE9FE', padding: 12, borderRadius: Theme.radius.lg },
  aiNoteText: { fontSize: Theme.font.size.small, color: Colors.ai, lineHeight: 20 },
});
